name: owner
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  shared_preferences: ^2.2.2
  get: ^4.6.6
  skeletons: ^0.0.3
  image_picker: ^1.0.7
  syncfusion_flutter_calendar: ^24.1.47
  jiffy: ^5.0.0
  connectivity_plus: ^5.0.2
  google_nav_bar: ^5.0.6
  syncfusion_flutter_charts: ^24.1.47+2
  flutter_widget_from_html: ^0.14.11
  flutter_otp_text_field: ^1.1.1
  webview_flutter: ^4.4.4
  url_launcher: ^6.2.4
  country_picker: ^2.0.23
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: semibold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
